### ISSUE TITLE
A value of type 'ListTileThemeData' can't be assigned to a variable of type 'ListTileTheme'.

### ISSUE THREAD

**Issue by Jandries** [yako-dev/flutter-settings-ui#99]
After updating to the latest version of Flutter I received this error:

> .pub-cache/git/flutter-settings-ui-dd14938d5c58863b0a0f32897267d35ce6ea8ba4/lib/src/cupertino_settings_item.dart:80:51: Error: A value of type 'ListTileThemeData' can't be assigned to a variable of type 'ListTileTheme'.

I fixed it in the file by changing two references to type `ListTileThemeData` instead of `ListTileTheme`:

`76. final ListTileTheme tileTheme = ListTileTheme.of(context);`
to
`76. final ListTileThemeData tileTheme = ListTileTheme.of(context);`

and
`314.   Color? _iconColor(ThemeData theme, ListTileTheme tileTheme) {`
to
`314.  Color? _iconColor(ThemeData theme, ListTileThemeData tileTheme) {`

If you could please add this to the next release it would be great! Thanks

**Comment by dariocavada** [comment]
tried the zeusbaba fix issue #99 related to ListTileTheme and it worked for me.

**Comment by christophermp** [comment]
Issue presented itself in Flutter V 2.8, settings_ui 1.0.0
Havent tried crearing the casher. But i assume the fix is pushed? The above solution worked for me.

**Comment by elirehema** [comment]
Hi @christophermp will you consider to merge the changes. Please

**Comment by noordawod** [comment]
After this repo was ignored for a looong time, I decided to move future work to https://github.com/juliansteenbakker/flutter_settings_ui. Culprit: https://github.com/yako-dev/flutter-settings-ui/pull/97

If you want merge my pr from there, you should be good in your repo too.

**Comment by yadaniyil** [comment]
Hey @Jandries @dariocavada @christophermp @elirehema  There is a new 2.0.0 version of the package, could you please if your issue is fixed there? Thanks :)

**Comment by noordawod** [comment]
I created a pr to fix few problems in Oct 2021, last update for v2.0.0 is Aug 2021. So no, the problems persist. This is what happens with unmaintained code ;)

**Comment by yadaniyil** [comment]
@noordawod The update was uploaded today. August is not 2.0.0, it's just the latest commit on the master branch. Dev branch is the freshest one and code commits were there in December. Let me know if you really tried the new version or just decided that the bug persists looking on the wrong dates?

**Comment by noordawod** [comment]
I haven't checked the version :) I'll take a look.

**Comment by noordawod** [comment]
Like I mentioned before, you need to apply my (now closed) pr in order to fix problems with recent Flutter versions:

```
/path/to/flutter_settings_ui-2.0.0/lib/src/cupertino_settings_item.dart:124:52: Error: A value of type 'Diagnosticable' can't be assigned to a variable of type 'ListTileTheme'.
 - 'Diagnosticable' is from 'package:flutter/src/foundation/diagnostics.dart' ('/path/to/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
 - 'ListTileTheme' is from 'package:flutter/src/material/list_tile.dart' ('/path/to/flutter/packages/flutter/lib/src/material/list_tile.dart').
    final ListTileTheme tileTheme = listTileThemes ?? ListTileTheme.of(context);
                                                   ^

FAILURE: Build failed with an exception.
```

`flutter doctor` = `Flutter (Channel master, 2.9.0-1.0.pre.294), Dart version 2.16.0 (build 2.16.0-144.0.dev)`

**Comment by yadaniyil** [comment]
@noordawod I'm not sure that you use the latest version, as we don't have `src/cupertino_settings_item.dart` any more in codebase

**Comment by noordawod** [comment]
Ok, now I see that the code was using an old cached package. Removed and `pub get` again, this time the right package was pulled from `pub.dev`.

With that being said, there are some major changes in this version (plus few bugs I already saw), so I'll wait with migrating.
